# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#  
# this theme based on  Yummy Theme

# Site settings
title: Cloud Chou's Tech Blog
name: Cloud Chou # ex. DONGChuan
email: 515312382@qq.com
location: 深圳市
company: 腾讯
website: www.cloudchou.com
url:  http://www.cloudchou.com
github: cloudchou
github_url: https://github.com/cloudchou
description: 专注于Android软件开发的码农,带你深入分析Android系统.目前有Android编译系统系列,源码开发环境的搭建,native binder,framework binder,应用层binder的使用实例,后续还会详细分析binder的框架层库和本地层库,另外对Handler的实现原理和它在源码中的使用也做了详细分析。
favicon: favicon.png
repository: cloudchou/cloudchou.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\r\n\r\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1  

# duoshuo
#disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

duoshuo :
  short_name : cloudchou2

lean_cloud :
  app_id   :  hQbdf5f1KrAGwtP4cXqprx7y-gzGzoHsz
  app_key  :  7F5Wwjbvx11t0bBmyIgmtpy5

# Pagination
paginate: 8
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: 首页

  -
    href: /bloglist
    label: 博客纪事

  -
    href: /about
    label: 关于
